services:
  database:
    image: timescale/timescaledb:latest-pg14
    container_name: cattle-db
    networks:
      - nexus-net
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=virtual_fencing_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d virtual_fencing_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: cattle-backend
    networks:
      - nexus-net
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/virtual_fencing_db
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: cattle-frontend
    networks:
      - nexus-net
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  simulator:
    build: ./simulator
    container_name: cattle-simulator
    networks:
      - nexus-net
    environment:
      - BACKEND_URL=http://backend:3001/api/collars/data
      - ACTIVITY_API_URL=http://backend:3001/api/imu-activity
      - FENCE_SYNC_URL=http://backend:3001/api/fences/sync
    depends_on:
      - backend
    volumes:
      - ./simulator:/app

volumes:
  db-data:


networks:
  nexus-net:
    driver: bridge
